export const featureDescriptions: Record<string, string> = {
  filing_method: 'Filing method and refund delivery',
  filing_time_category: 'Filing timing',
  bank_deposit_type: 'Type of bank account for direct deposit',
  geo_region: 'Your geographic region',
  prior_credits_claimed: 'Credits claimed in prior years',
  has_return_errors: 'Return has errors',
  requires_id_verification: 'Identity verification required',
  is_selected_for_manual_review: 'Selected for manual review',
  claimed_eitc: 'Claimed Earned Income Tax Credit',
  claimed_actc: 'Claimed Additional Child Tax Credit',
  is_amended_return: 'Filed an amended return',
  has_injured_spouse_claim: 'Injured spouse claim present',
  has_offset_debts: 'Refund offset due to debts',
  prior_refund_delayed: 'Previously delayed refund',
  prior_id_verification_flagged: 'Previously required ID verification',
  has_bank_info_on_file: 'IRS has bank info on file',
  num_days_since_filed: 'Days since return filed',
  return_completeness_score: 'Return completeness score',
  prior_refund_processing_time: 'Prior refund processing time',
  filing_method_efile_direct_deposit: 'Filed electronically with direct deposit',
  filing_method_efile_paper_check: 'Filed electronically with paper check',
  filing_method_paper_direct_deposit: 'Paper-filed return with direct deposit',
  filing_method_paper_paper_check: 'Paper-filed return with paper check',
  prior_credits_claimed_none: 'Claimed no prior credits',
  prior_credits_claimed_few: 'Claimed few prior credits',
  prior_credits_claimed_many: 'Claimed many prior credits'
};
