import {
  AlertTriangle,
  Banknote,
  Clock,
  DollarSign,
  FileCheck,
  FileEdit,
  FileText,
  FolderCheck,
  Globe,
  Key,
  Layers,
  List,
  Search,
  Slash,
  UserCheck,
  Users,
  Wallet
} from 'lucide-react';

export const featureIcons: Record<string, React.ReactNode> = {
  filing_method: <FileText className="h-4 w-4 text-muted-foreground" />,
  filing_time_category: <Clock className="h-4 w-4 text-muted-foreground" />,
  bank_deposit_type: <Banknote className="h-4 w-4 text-muted-foreground" />,
  geo_region: <Globe className="h-4 w-4 text-muted-foreground" />,
  prior_credits_claimed: <Layers className="h-4 w-4 text-muted-foreground" />,
  has_return_errors: <AlertTriangle className="h-4 w-4 text-muted-foreground" />,
  requires_id_verification: <Key className="h-4 w-4 text-muted-foreground" />,
  is_selected_for_manual_review: <Search className="h-4 w-4 text-muted-foreground" />,
  claimed_eitc: <DollarSign className="h-4 w-4 text-muted-foreground" />,
  claimed_actc: <DollarSign className="h-4 w-4 text-muted-foreground" />,
  is_amended_return: <FileEdit className="h-4 w-4 text-muted-foreground" />,
  has_injured_spouse_claim: <Users className="h-4 w-4 text-muted-foreground" />,
  has_offset_debts: <Slash className="h-4 w-4 text-muted-foreground" />,
  prior_refund_delayed: <Clock className="h-4 w-4 text-muted-foreground" />,
  prior_id_verification_flagged: <UserCheck className="h-4 w-4 text-muted-foreground" />,
  has_bank_info_on_file: <Wallet className="h-4 w-4 text-muted-foreground" />,
  num_days_since_filed: <Clock className="h-4 w-4 text-muted-foreground" />,
  return_completeness_score: <FolderCheck className="h-4 w-4 text-muted-foreground" />,
  prior_refund_processing_time: <Clock className="h-4 w-4 text-muted-foreground" />,
  filing_method_efile_direct_deposit: <FileCheck className="h-4 w-4 text-muted-foreground" />,
  filing_method_efile_paper_check: <FileCheck className="h-4 w-4 text-muted-foreground" />,
  filing_method_paper_direct_deposit: <FileCheck className="h-4 w-4 text-muted-foreground" />,
  filing_method_paper_paper_check: <FileCheck className="h-4 w-4 text-muted-foreground" />,
  prior_credits_claimed_none: <List className="h-4 w-4 text-muted-foreground" />,
  prior_credits_claimed_few: <List className="h-4 w-4 text-muted-foreground" />,
  prior_credits_claimed_many: <List className="h-4 w-4 text-muted-foreground" />
};
